default: &default
  adapter: sqlite3
  # encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # username: <%= Rails.application.credentials.database[:username] %>
  # password: <%= Rails.application.credentials.database[:password] %>

development:
  <<: *default
  # database: bagelpatch_dev
  database: db/development.sqlite3

test:
  <<: *default
  # database: bagelpatch_test
  database: db/test.sqlite3

production:
  <<: *default
  # database: bagelpatch_production
  # host: dpg-cisuhglph6et1sa50ktg-a.oregon-postgres.render.com
  database: db/production.sqlite3
