default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: ubuntu
  password: password
  # TODO yikes, change this

development:
  <<: *default
  username: coreyschneider
  password: 
  database: bagelpatch_dev

test:
  <<: *default
  database: bagelpatch_test

production:
  <<: *default
  # database: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
  url: <%= ENV['DATABASE_URL'] %>