default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>

development:
  <<: *default
  database: bagelpatch_dev

test:
  <<: *default
  database: bagelpatch_test

production:
  <<: *default
  database: bagelpatch_production
